# Schema

![](https://github.com/motional/nuplan-devkit/raw/master/docs/nuplan_schema.png)

## set environment variables

In [1]:
import os
NUPLAN_DATA_ROOT = os.getenv('NUPLAN_DATA_ROOT', './nuplan')
NUPLAN_MAPS_ROOT = os.getenv('NUPLAN_MAPS_ROOT', './nuplan/dataset/maps')
NUPLAN_DB_FILES = os.getenv('NUPLAN_DB_FILES', './nuplan/dataset/nuplan-v1.1/mini')
NUPLAN_MAP_VERSION = os.getenv('NUPLAN_MAP_VERSION', 'nuplan-maps-v1.0')

# ORM Database API

## load data

In [2]:
from nuplan.database.nuplan_db_orm.nuplandb_wrapper import NuPlanDBWrapper

nuplandb_wrapper = NuPlanDBWrapper(
    data_root=NUPLAN_DATA_ROOT,
    map_root=NUPLAN_MAPS_ROOT,
    db_files=NUPLAN_DB_FILES,
    map_version=NUPLAN_MAP_VERSION,
)

## query a database

In [3]:
log_db_name = "2021.05.12.22.00.38_veh-35_01008_01518"
log_db = nuplandb_wrapper.get_log_db(log_db_name)

Get all file name

In [4]:
from os import listdir
from os.path import isfile, join
file_names_with_extension = [f for f in listdir(NUPLAN_DB_FILES) if isfile(join(NUPLAN_DB_FILES, f))]

file_names = [name[:-3] for name in file_names_with_extension]
file_names

['2021.10.11.07.12.18_veh-50_00211_00304',
 '2021.08.17.17.17.01_veh-45_02314_02798',
 '2021.06.09.17.23.18_veh-38_00773_01140',
 '2021.10.11.02.57.41_veh-50_00352_00535',
 '2021.06.09.12.39.51_veh-26_05620_06003',
 '2021.08.17.18.54.02_veh-45_00665_01065',
 '2021.06.14.18.33.41_veh-35_03901_04264',
 '2021.05.12.23.36.44_veh-35_02035_02387',
 '2021.08.24.13.12.55_veh-45_00386_00472',
 '2021.10.11.08.31.07_veh-50_01750_01948',
 '2021.07.24.23.50.16_veh-17_01696_02071',
 '2021.10.01.19.16.42_veh-28_03307_03808',
 '2021.10.05.07.10.04_veh-52_01442_01802',
 '2021.07.16.20.45.29_veh-35_00600_01084',
 '2021.07.16.20.45.29_veh-35_01095_01486',
 '2021.10.06.07.26.10_veh-52_00006_00398',
 '2021.07.24.20.37.45_veh-17_00015_00375',
 '2021.06.08.12.54.54_veh-26_04262_04732',
 '2021.06.08.16.31.33_veh-38_01589_02072',
 '2021.07.16.18.06.21_veh-38_03231_03712',
 '2021.09.16.15.12.03_veh-42_01037_01434',
 '2021.06.23.20.43.31_veh-16_03607_04007',
 '2021.05.12.22.28.35_veh-35_00620_01164',
 '2021.06.2

## acess data

In [5]:
len(log_db.scenario_tag)

13812

In [6]:
len(log_db.lidar_pc)

10200

In [7]:
raw_scenario = [log_db.scenario_tag[i].type for i in range(len(log_db.scenario_tag))]
set(raw_scenario)

{'high_magnitude_speed',
 'low_magnitude_speed',
 'medium_magnitude_speed',
 'near_construction_zone_sign',
 'near_high_speed_vehicle',
 'near_pedestrian_on_crosswalk',
 'on_intersection',
 'on_stopline_traffic_light',
 'on_traffic_light_intersection',
 'starting_straight_stop_sign_intersection_traversal',
 'starting_straight_traffic_light_intersection_traversal',
 'stationary',
 'stationary_in_traffic',
 'traversing_crosswalk',
 'traversing_intersection',
 'traversing_traffic_light_intersection'}

In [8]:
log_db.lidar_box

LidarBox(1280922 entries):
--------------------------------------------------
token                       : f8745354d77f5e37
x                           : 664682.04248548
vy                          : -0.0020695771418821544
y                           : 3999281.5750495587
vz                          : -0.0018686033398442694
z                           : 606.1606478954054
yaw                         : -0.2767499453159221
lidar_pc_token              : e1e4ee25d1ff58f2
width                       : 0.40028481511936265
confidence                  : 0.5808950916575207
length                      : 0.397288774073045
track_token                 : 7af4e8cc4e86597a
height                      : 1.2509109225489499
next_token                  : b30624229d7d5a9a
vx                          : 0.008847108592404675
prev_token                  : None

token                       : 70153170580b51e5
x                           : 664689.4877757924
vy                          : -1.0953151492005082
y      

## filter

### import data type

In [9]:
from nuplan.database.nuplan_db_orm.lidar_pc import LidarPc
from nuplan.database.nuplan_db_orm.category import Category
from nuplan.database.nuplan_db_orm.ego_pose import EgoPose
from nuplan.database.nuplan_db_orm.lidar_box import LidarBox
from nuplan.database.nuplan_db_orm.log import Log
from nuplan.database.nuplan_db_orm.scene import Scene
from nuplan.database.nuplan_db_orm.scenario_tag import ScenarioTag
from nuplan.database.nuplan_db_orm.traffic_light_status import TrafficLightStatus
from nuplan.database.nuplan_db_orm.track import Track

### query and filter

In [10]:
scenario_tag_single = log_db.session.query(ScenarioTag) \
  .filter(ScenarioTag.agent_track_token != None) \
  .limit(10) \
  .all()

scenario_tag_single

[token                       : e83c784f4c005d26
 agent_track_token           : 6c253dd25e285c02
 lidar_pc_token              : 67fc50f5f2b354c8
 type                        : near_high_speed_vehicle
 ,
 token                       : 0bc0a62f8770519a
 agent_track_token           : 6c253dd25e285c02
 lidar_pc_token              : c99340a8526059ea
 type                        : near_high_speed_vehicle
 ,
 token                       : 5fc0e344b3b95773
 agent_track_token           : 6c253dd25e285c02
 lidar_pc_token              : 26a3b06a44f85761
 type                        : near_high_speed_vehicle
 ,
 token                       : 41fd65c8d65158bd
 agent_track_token           : 6c253dd25e285c02
 lidar_pc_token              : 83a8090c55045e8b
 type                        : near_high_speed_vehicle
 ,
 token                       : 93c86322bd0f5272
 agent_track_token           : 6c253dd25e285c02
 lidar_pc_token              : 04602bed0b8b5c1b
 type                        : near_high_speed_v

In [11]:
lidar_pc_token = scenario_tag_single[0].lidar_pc_token
agent_track_token = scenario_tag_single[0].agent_track_token

In [12]:
lidar_pc = log_db.session.query(LidarPc) \
  .filter(LidarPc.token == lidar_pc_token) \
  .all()
          
lidar_pc

[token                       : 67fc50f5f2b354c8
 prev_token                  : 4050dceb7cfb529b
 lidar_token                 : b95e61f2a75f5273
 scene_token                 : 964f7276202b566a
 timestamp                   : 1620857943850113
 next_token                  : c99340a8526059ea
 ego_pose_token              : bcb13eb64c205434
 filename                    : 2021.05.12.22.00.38_veh-35_01008_01518/MergedPointCloud/67fc50f5f2b354c8.pcd
 ]

In [13]:
prev_token = lidar_pc[0].prev_token
lidar_pc = log_db.session.query(LidarPc) \
  .filter(LidarPc.token == prev_token) \
  .all()
          
lidar_pc

[token                       : 4050dceb7cfb529b
 prev_token                  : 26d245d87c805769
 lidar_token                 : b95e61f2a75f5273
 scene_token                 : 964f7276202b566a
 timestamp                   : 1620857943800102
 next_token                  : 67fc50f5f2b354c8
 ego_pose_token              : 4fc68f21814a5474
 filename                    : 2021.05.12.22.00.38_veh-35_01008_01518/MergedPointCloud/4050dceb7cfb529b.pcd
 ]

# NuPlanScenarios

### import

In [14]:
import itertools
import logging
import random
from collections import defaultdict
from dataclasses import dataclass
from os.path import join
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import numpy.typing as npt

from nuplan.common.actor_state.vehicle_parameters import get_pacifica_parameters
from nuplan.common.maps.nuplan_map.map_factory import NuPlanMapFactory, get_maps_db
from nuplan.database.nuplan_db.nuplan_scenario_queries import (
    get_lidarpc_token_map_name_from_db,
    get_lidarpc_token_timestamp_from_db,
    get_lidarpc_tokens_with_scenario_tag_from_db,
)
from nuplan.planning.nuboard.base.data_class import NuBoardFile, SimulationScenarioKey
from nuplan.planning.nuboard.base.experiment_file_data import ExperimentFileData
from nuplan.planning.nuboard.base.simulation_tile import SimulationTile
from nuplan.planning.scenario_builder.abstract_scenario import AbstractScenario
from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario import NuPlanScenario
from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_filter_utils import discover_log_dbs
from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_utils import (
    DEFAULT_SCENARIO_NAME,
    ScenarioExtractionInfo,
)

from tutorials.utils.tutorial_utils import get_scenario_type_token_map, get_default_scenario_from_token

In [15]:
data_root=NUPLAN_DATA_ROOT
map_root=NUPLAN_MAPS_ROOT
db_files=NUPLAN_DB_FILES
map_version=NUPLAN_MAP_VERSION

### Using `NuPlanScenario` class.
Query a desired scenario via `NuPlanScenario` class, e.g., 'near_high_speed_vehicle'.

In [16]:
query_scenario = 'near_high_speed_vehicle'

log_db_files = discover_log_dbs(db_files)
scenario_type_token_map = get_scenario_type_token_map(log_db_files)

In [17]:
log_db_file, token = random.choice(scenario_type_token_map[query_scenario])
scenario = get_default_scenario_from_token(data_root, log_db_file, token, map_root, map_version)

API params descriptions in `abstract_scenario.py`

### duration of the scenario

In [18]:
scenario.duration_s.time_s

14.899464

### number of frame the scenario contains

In [19]:
scenario.get_number_of_iterations()

150

### frame interval

In [20]:
scenario.database_interval # s

0.1

### initial ego state

location

In [21]:
scenario.initial_ego_state.agent.center

StateSE2(x=664434.6085011496, y=3997240.0038875234, heading=-1.5475539448455533)

velocity

In [22]:
scenario.initial_ego_state.agent.velocity

x: 12.59036829619357, y: -0.1957710669252266

acceleration

In [23]:
scenario.initial_ego_state.dynamic_car_state.center_acceleration_2d

x: -0.2883749261918731, y: 0.1403573955238959

In [24]:
scenario.get_ego_state_at_iteration(iteration=1).agent.center

StateSE2(x=664434.640302516, y=3997238.7737377593, heading=-1.5469815703448255)

In [25]:
scenario.get_ego_state_at_iteration(iteration=1).agent.velocity

x: 12.553641130661429, y: -0.19418423924083755

In [26]:
scenario.get_ego_state_at_iteration(iteration=1).dynamic_car_state.center_acceleration_2d

x: -0.2516497452117911, y: 0.16854740805081972

In [27]:
ego_current_state = scenario.get_ego_state_at_iteration(iteration=1)

ego_current_array = np.array(
    [ego_current_state.agent.center.x,
     ego_current_state.agent.center.y,
     ego_current_state.agent.center.heading,
     ego_current_state.dynamic_car_state.center_velocity_2d.x,
     ego_current_state.dynamic_car_state.center_velocity_2d.y,
     ego_current_state.dynamic_car_state.center_acceleration_2d.x,
     ego_current_state.dynamic_car_state.center_acceleration_2d.y]
)


### ego past trajectory

In [28]:
ego_past_trajectory = scenario.get_ego_past_trajectory(
    iteration=0,
    time_horizon=5,
)

ego_past_trajectory

<generator object get_sampled_ego_states_from_db at 0x7fe0ad8e4dd0>

In [29]:
past_trajectory = list(ego_past_trajectory)
past_trajectory

In [30]:
past_trajectory[2].agent.center

StateSE2(x=664433.0465491773, y=3997301.843207928, heading=-1.551499271131539)

In [31]:
past_trajectory[2].dynamic_car_state.center_velocity_2d

x: 12.82100713793684, y: -0.24120568216158036

In [32]:
past_trajectory[2].dynamic_car_state.center_acceleration_2d

x: 0.6942829460659568, y: 0.014820403252692843

In [33]:
ego_past_array = np.array(
    [[past_state.agent.center.x,
      past_state.agent.center.y,
      past_state.agent.center.heading,
      past_state.dynamic_car_state.center_velocity_2d.x,
      past_state.dynamic_car_state.center_velocity_2d.y,
      past_state.dynamic_car_state.center_acceleration_2d.x,
      past_state.dynamic_car_state.center_acceleration_2d.y] for past_state in past_trajectory]
)

ego_past_array.shape

(50, 7)

### ego future trajectory

In [34]:
ego_future_trajectory = scenario.get_ego_future_trajectory(
    iteration=0, # iteration within scenario 0 <= scenario_iteration < get_number_of_iterations
    time_horizon=10, # the desired horizon to the future, s
)

ego_future_trajectory

<generator object get_sampled_ego_states_from_db at 0x7fe0752043c0>

In [35]:
future_trajectory = list(ego_future_trajectory)
future_trajectory

center

In [36]:
future_trajectory[0].agent.center

StateSE2(x=664434.640302516, y=3997238.7737377593, heading=-1.5469815703448255)

velocity

In [37]:
future_trajectory[0].dynamic_car_state.center_velocity_2d

x: 12.553641130661429, y: -0.19418423924083755

acceleration

In [38]:
future_trajectory[0].dynamic_car_state.center_acceleration_2d

x: -0.2516497452117911, y: 0.16854740805081972

In [39]:
future_trajectory[0].time_seconds

1623275421.600045

In [40]:
future_trajectory[-1].time_seconds

1623275431.4997098

In [41]:
ego_future_array = np.array(
    [[future_state.agent.center.x,
      future_state.agent.center.y,
      future_state.agent.center.heading,
      future_state.dynamic_car_state.center_velocity_2d.x,
      future_state.dynamic_car_state.center_velocity_2d.y,
      future_state.dynamic_car_state.center_acceleration_2d.x,
      future_state.dynamic_car_state.center_acceleration_2d.y] for future_state in future_trajectory]
)

ego_future_array

array([[ 6.64434640e+05,  3.99723877e+06, -1.54698157e+00,
         1.25536411e+01, -1.94184239e-01, -2.51649745e-01,
         1.68547408e-01],
       [ 6.64434669e+05,  3.99723754e+06, -1.54688742e+00,
         1.25225836e+01, -1.95806566e-01, -2.96618104e-01,
        -9.34365204e-02],
       [ 6.64434698e+05,  3.99723632e+06, -1.54688162e+00,
         1.24942093e+01, -2.03387195e-01, -1.42405584e-01,
         1.46922707e-01],
       [ 6.64434727e+05,  3.99723508e+06, -1.54738337e+00,
         1.24558987e+01, -1.87918486e-01, -1.84195998e-01,
        -3.18362557e-02],
       [ 6.64434754e+05,  3.99723386e+06, -1.54785858e+00,
         1.24295738e+01, -2.07267058e-01, -1.27118761e-01,
        -2.33071051e-01],
       [ 6.64434781e+05,  3.99723263e+06, -1.54845980e+00,
         1.24055106e+01, -2.26838975e-01, -3.24587839e-01,
        -5.04941839e-01],
       [ 6.64434804e+05,  3.99723142e+06, -1.54821104e+00,
         1.23798788e+01, -2.39792345e-01, -6.75054179e-01,
         2.4002032

In [42]:
np.linalg.norm(np.asarray([ego_future_array[-1][3], ego_future_array[-1][4]]))

8.82924570878167

### objects within time window

In [43]:
tracked_objs_within_t = scenario.get_tracked_objects_within_time_window_at_iteration(
    iteration=0,
    past_time_horizon=5,
    future_time_horizon=0
)

tracked_objs_within_t

DetectionsTracks(tracked_objects=<nuplan.common.actor_state.tracked_objects.TrackedObjects object at 0x7fe057cd1490>)

In [44]:
tracked_objs_within_t.tracked_objects.get_static_objects()

 ...]

In [45]:
set([obj.metadata.category_name for obj in tracked_objs_within_t.tracked_objects.get_static_objects()])

{'generic_object', 'traffic_cone'}

In [46]:
tracked_objs_within_t.tracked_objects.get_static_objects()[2].center

StateSE2(x=664481.8972993412, y=3997267.4796276386, heading=-0.7880825768495061)

In [47]:
tracked_objs_within_t.tracked_objects.get_agents()

 ...]

location

In [48]:
set([obj.metadata.category_name for obj in tracked_objs_within_t.tracked_objects.get_agents()])

{'pedestrian', 'vehicle'}

In [49]:
tracked_objs_within_t.tracked_objects.get_agents()[0].center

StateSE2(x=664396.9161562142, y=3997296.415331367, heading=2.7711712755297295)

velocity

In [50]:
tracked_objs_within_t.tracked_objects.get_agents()[0].velocity.x

-0.8543448742963617

**acceleration is NOT given in tracking**

In [51]:
obj = tracked_objs_within_t.tracked_objects.get_agents()[3]

In [52]:
obj.metadata

SceneObjectMetadata(timestamp_us=1623275416549737, token='398de75346315c65', track_id=23, track_token='419f4f72a1615bdd', category_name='pedestrian')

### agent at time point

In [53]:
object_current_state = scenario.get_tracked_objects_at_iteration(iteration=1).tracked_objects.get_agents()

In [54]:
obj = scenario.get_tracked_objects_at_iteration(iteration=1).tracked_objects.get_agents()[0]

In [55]:
obj.velocity

x: -0.15790873624363616, y: -0.9874564561210671

In [56]:
obj.track_token

'ca405ce7f1665310'

In [57]:
object_current_array = np.array(
    [[obj_state.center.x,
      obj_state.center.y,
      obj_state.center.heading,
      obj_state.velocity.x,
      obj_state.velocity.y,
      0,
      0] for obj_state in object_current_state]
)
object_current_track_token = np.array(
    [obj_state.track_token for obj_state in object_current_state]
)

In [58]:
object_current_array

array([[ 6.64481315e+05,  3.99726878e+06, -1.66071079e+00,
        -1.57908736e-01, -9.87456456e-01,  0.00000000e+00,
         0.00000000e+00],
       [ 6.64482337e+05,  3.99726862e+06, -1.62227810e+00,
        -2.88064036e-02, -1.08912694e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.64481969e+05,  3.99726724e+06, -1.61716581e+00,
        -2.73769231e-02, -1.07186132e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.64482761e+05,  3.99726642e+06, -1.59817588e+00,
         2.20975840e-02, -1.06280617e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.64483008e+05,  3.99726702e+06, -1.64140049e+00,
        -8.74522274e-02, -1.06290432e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.64481310e+05,  3.99725384e+06, -1.45889314e+00,
         1.30246818e-01, -1.16991933e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.64480878e+05,  3.99725299e+06, -1.47629624e+00,
         1.05936222e-01, -1.14701743e+00,  0.00000000e+00,
         0.0000000

In [59]:
object_current_track_token

array(['ca405ce7f1665310', '954cebc7eca45cd4', 'ae0628dc425956eb',
       'd54ad0fcaa57552f', '6aef1d15a12f53bc', '6abfba31a61152fd',
       'f19560f192045346', '3c7665fa51e753ce', '32f8c69ad9c6514c',
       '38a708c7ae125b0e', '1b04c1c1c2d85265', '7d6f70b00d635910',
       '62e1c1b7625658bd', '489988970ce65078', '672d970bf702554a',
       '21df15bc59935f37', '05a1097025ce550f', 'c8c2348d2f215907',
       '23df8c705b575438', 'fb0edb90446d5733', '1edd426b98335574',
       '7d823b46c898501d', 'b5b386890593573e', '19a6180c6ead5d69',
       '4804be390ed85d70', 'f5d0212b20f85cdc', '636b7da7f312550e',
       '0637a9d267475f61', '029669228ef35858', 'a308312886ff5de4',
       '1f1c2364d82e56a7', 'f8a77f06a32c5b87', '0a799a90a3045909',
       'f8dd5817bf8c5870', 'd5fcf98e830b59d2', '61f2dba4068a5d3e',
       'b5d2b1123401561f', '9fc2954e8fc75ad9', '0094d9b090545d7f',
       'a2766e0fdb5c5fda', '3c7d09025a7755eb', '2a72dced3f7d577f',
       '63def412c436558c', '838ac3ac8bdb5218', '600237fec2bf5f

In [60]:
ego_x = ego_current_array[0]
ego_y = ego_current_array[1]

objects_current_info = []
objects_distance = []
objects_track_token = []
for obj_current_state in object_current_state:
    obj_x = obj_current_state.center.x
    obj_y = obj_current_state.center.y
    dx = obj_x - ego_x
    dy = obj_y - ego_y
    distance = np.linalg.norm(np.asarray([dx, dy]))

    if distance <= 1000:
        objects_current_info.append(
            [obj_current_state.center.x,
             obj_current_state.center.y,
             obj_current_state.center.heading,
             obj_current_state.velocity.x,
             obj_current_state.velocity.y,
             0,
             0,
            distance]
        )
        objects_distance.append(distance)
        objects_track_token.append(obj_current_state.track_token)
objects_current_info = np.asarray(objects_current_info)
objects_distance = np.asarray(objects_distance)
objects_track_token = np.asarray(objects_track_token)

In [61]:
objects_current_info

array([[ 6.64481315e+05,  3.99726878e+06, -1.66071079e+00,
        -1.57908736e-01, -9.87456456e-01,  0.00000000e+00,
         0.00000000e+00,  5.54860503e+01],
       [ 6.64482337e+05,  3.99726862e+06, -1.62227810e+00,
        -2.88064036e-02, -1.08912694e+00,  0.00000000e+00,
         0.00000000e+00,  5.62633390e+01],
       [ 6.64481969e+05,  3.99726724e+06, -1.61716581e+00,
        -2.73769231e-02, -1.07186132e+00,  0.00000000e+00,
         0.00000000e+00,  5.52308326e+01],
       [ 6.64482761e+05,  3.99726642e+06, -1.59817588e+00,
         2.20975840e-02, -1.06280617e+00,  0.00000000e+00,
         0.00000000e+00,  5.54963534e+01],
       [ 6.64483008e+05,  3.99726702e+06, -1.64140049e+00,
        -8.74522274e-02, -1.06290432e+00,  0.00000000e+00,
         0.00000000e+00,  5.60137939e+01],
       [ 6.64481310e+05,  3.99725384e+06, -1.45889314e+00,
         1.30246818e-01, -1.16991933e+00,  0.00000000e+00,
         0.00000000e+00,  4.90426695e+01],
       [ 6.64480878e+05,  3.997252

In [62]:
objects_distance

array([55.48605028, 56.26333905, 55.23083258, 55.49635339, 56.01379387,
       49.04266946, 48.37253562, 49.7223711 , 17.27206019, 18.9282631 ,
       51.20750583, 23.46705628, 51.72526991, 44.14061252, 16.75532412,
       44.11889168, 40.31266874, 42.79147708, 52.43048064, 19.61821185,
       20.98827859, 22.22778248, 21.30592792, 64.34159092, 63.3555189 ,
       64.76306871, 53.95820117, 64.65116821, 41.05286201, 65.84469168,
       53.83133261, 65.34985949, 18.04610481, 66.48573438, 27.88748491,
       76.0033733 , 11.81620055, 18.47878215, 26.08852765, 66.57807035,
       75.86614771, 50.3591267 , 22.24756192,  9.83331572, 37.98876965,
       35.42071474, 46.86184752, 44.43187721, 38.56985832, 72.67451575,
       56.96238273, 46.25079495, 40.14050393, 37.23780299, 54.93398981])

In [63]:
objects_track_token

array(['ca405ce7f1665310', '954cebc7eca45cd4', 'ae0628dc425956eb',
       'd54ad0fcaa57552f', '6aef1d15a12f53bc', '6abfba31a61152fd',
       'f19560f192045346', '3c7665fa51e753ce', '32f8c69ad9c6514c',
       '38a708c7ae125b0e', '1b04c1c1c2d85265', '7d6f70b00d635910',
       '62e1c1b7625658bd', '489988970ce65078', '672d970bf702554a',
       '21df15bc59935f37', '05a1097025ce550f', 'c8c2348d2f215907',
       '23df8c705b575438', 'fb0edb90446d5733', '1edd426b98335574',
       '7d823b46c898501d', 'b5b386890593573e', '19a6180c6ead5d69',
       '4804be390ed85d70', 'f5d0212b20f85cdc', '636b7da7f312550e',
       '0637a9d267475f61', '029669228ef35858', 'a308312886ff5de4',
       '1f1c2364d82e56a7', 'f8a77f06a32c5b87', '0a799a90a3045909',
       'f8dd5817bf8c5870', 'd5fcf98e830b59d2', '61f2dba4068a5d3e',
       'b5d2b1123401561f', '9fc2954e8fc75ad9', '0094d9b090545d7f',
       'a2766e0fdb5c5fda', '3c7d09025a7755eb', '2a72dced3f7d577f',
       '63def412c436558c', '838ac3ac8bdb5218', '600237fec2bf5f

In [64]:
objects_current_info[objects_distance.argsort()]

array([[ 6.64437923e+05,  3.99724804e+06, -1.53997526e+00,
         5.18976953e-01, -1.74512895e+01,  0.00000000e+00,
         0.00000000e+00,  9.83331572e+00],
       [ 6.64431846e+05,  3.99722729e+06, -1.54803338e+00,
         1.47557890e-01, -8.92152974e+00,  0.00000000e+00,
         0.00000000e+00,  1.18162005e+01],
       [ 6.64425131e+05,  3.99722498e+06,  1.67737893e+00,
        -8.53336518e-02,  1.12814265e+00,  0.00000000e+00,
         0.00000000e+00,  1.67553241e+01],
       [ 6.64424447e+05,  3.99722483e+06,  1.65720631e+00,
        -8.18226454e-02,  1.11241095e+00,  0.00000000e+00,
         0.00000000e+00,  1.72720602e+01],
       [ 6.64417312e+05,  3.99723374e+06,  1.67159843e+00,
        -4.29660987e-02,  4.64512183e-01,  0.00000000e+00,
         0.00000000e+00,  1.80461048e+01],
       [ 6.64430700e+05,  3.99725683e+06, -1.54116586e+00,
         3.15220648e-01, -1.00827818e+01,  0.00000000e+00,
         0.00000000e+00,  1.84787822e+01],
       [ 6.64425587e+05,  3.997222

In [65]:
objects_track_token[objects_distance.argsort()]

array(['838ac3ac8bdb5218', 'b5d2b1123401561f', '672d970bf702554a',
       '32f8c69ad9c6514c', '0a799a90a3045909', '9fc2954e8fc75ad9',
       '38a708c7ae125b0e', 'fb0edb90446d5733', '1edd426b98335574',
       'b5b386890593573e', '7d823b46c898501d', '63def412c436558c',
       '7d6f70b00d635910', '0094d9b090545d7f', 'd5fcf98e830b59d2',
       '4696c42f7a825f97', '87768de811a351ef', '600237fec2bf5f76',
       'e226d4ef2c82535a', '95da2236f0775eac', '05a1097025ce550f',
       '029669228ef35858', 'c8c2348d2f215907', '21df15bc59935f37',
       '489988970ce65078', '0013b1093e955033', 'ddfa558c99c65372',
       '58f3100fb5005090', 'f19560f192045346', '6abfba31a61152fd',
       '3c7665fa51e753ce', '2a72dced3f7d577f', '1b04c1c1c2d85265',
       '62e1c1b7625658bd', '23df8c705b575438', '1f1c2364d82e56a7',
       '636b7da7f312550e', 'f44e424fe1365551', 'ae0628dc425956eb',
       'ca405ce7f1665310', 'd54ad0fcaa57552f', '6aef1d15a12f53bc',
       '954cebc7eca45cd4', 'dc0cd49d9beb5252', '4804be390ed85d

In [66]:
objects_distance[objects_distance.argsort()]

array([ 9.83331572, 11.81620055, 16.75532412, 17.27206019, 18.04610481,
       18.47878215, 18.9282631 , 19.61821185, 20.98827859, 21.30592792,
       22.22778248, 22.24756192, 23.46705628, 26.08852765, 27.88748491,
       35.42071474, 37.23780299, 37.98876965, 38.56985832, 40.14050393,
       40.31266874, 41.05286201, 42.79147708, 44.11889168, 44.14061252,
       44.43187721, 46.25079495, 46.86184752, 48.37253562, 49.04266946,
       49.7223711 , 50.3591267 , 51.20750583, 51.72526991, 52.43048064,
       53.83133261, 53.95820117, 54.93398981, 55.23083258, 55.48605028,
       55.49635339, 56.01379387, 56.26333905, 56.96238273, 63.3555189 ,
       64.34159092, 64.65116821, 64.76306871, 65.34985949, 65.84469168,
       66.48573438, 66.57807035, 72.67451575, 75.86614771, 76.0033733 ])

In [67]:
len(objects_current_info)

55

In [93]:
objects_current_info.shape

(55, 8)

In [71]:
obj_token = objects_track_token[4]
obj_token

'6aef1d15a12f53bc'

In [86]:
obj_token = '6aef1d15a12f53bc'
np.where(objects_track_token==obj_token)[0].item() if len(np.where(objects_track_token==obj_token)[0]) != 0 else None

4

In [95]:
objects_virtual_info = np.zeros((3, objects_current_info.shape[1]))
objects_virtual_info

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
np.concatenate((objects_current_info, objects_virtual_info), axis=0)

array([[ 6.64481315e+05,  3.99726878e+06, -1.66071079e+00,
        -1.57908736e-01, -9.87456456e-01,  0.00000000e+00,
         0.00000000e+00,  5.54860503e+01],
       [ 6.64482337e+05,  3.99726862e+06, -1.62227810e+00,
        -2.88064036e-02, -1.08912694e+00,  0.00000000e+00,
         0.00000000e+00,  5.62633390e+01],
       [ 6.64481969e+05,  3.99726724e+06, -1.61716581e+00,
        -2.73769231e-02, -1.07186132e+00,  0.00000000e+00,
         0.00000000e+00,  5.52308326e+01],
       [ 6.64482761e+05,  3.99726642e+06, -1.59817588e+00,
         2.20975840e-02, -1.06280617e+00,  0.00000000e+00,
         0.00000000e+00,  5.54963534e+01],
       [ 6.64483008e+05,  3.99726702e+06, -1.64140049e+00,
        -8.74522274e-02, -1.06290432e+00,  0.00000000e+00,
         0.00000000e+00,  5.60137939e+01],
       [ 6.64481310e+05,  3.99725384e+06, -1.45889314e+00,
         1.30246818e-01, -1.16991933e+00,  0.00000000e+00,
         0.00000000e+00,  4.90426695e+01],
       [ 6.64480878e+05,  3.997252